CREATE TABLE ESTUDIANTE (
IDESTUDIANTE INT PRIMARY KEY IDENTITY (1,1) NOT NULL,
NOMBRES VARCHAR(50) NOT NULL,
APELLIDOS VARCHAR(50) NOT NULL,
FECHANACIMIENTO DATE,
HABILITADO INT
);

CREATE TABLE PROFESOR (
IDPROFESOR INT PRIMARY KEY IDENTITY (1,1) NOT NULL,
NOMBRES VARCHAR(50) NOT NULL,
APELLIDOS VARCHAR(50) NOT NULL,
FECHANACIMIENTO DATE,
HABILITADO INT
);

CREATE TABLE ASIGNATURA (
IDCLASE INT PRIMARY KEY IDENTITY (1,1) NOT NULL,
DESCRIPCION VARCHAR(20) NOT NULL,
ACTIVA INT
);

CREATE TABLE EST_PROF (
SECUENCIA INT PRIMARY KEY IDENTITY (1,1) NOT NULL,
IDPROFESOR INT,
IDCLASE INT,
IDESTUDIANTE INT,
CONSTRAINT FK_PROFESOR FOREIGN KEY (IDPROFESOR) REFERENCES PROFESOR (IDPROFESOR),
CONSTRAINT FK_ESTUDIANTE FOREIGN KEY (IDESTUDIANTE) REFERENCES ESTUDIANTE (IDESTUDIANTE),
CONSTRAINT FK_CLASE FOREIGN KEY (IDCLASE) REFERENCES ASIGNATURA (IDCLASE)
);