--INSERT TABLA ESTUDIANTE
BEGIN TRAN
INSERT INTO ESTUDIANTE (NOMBRES, APELLIDOS, FECHANACIMIENTO, HABILITADO) VALUES ('JUAN CARLOS', 'PEREA RODRIGUEZ', '01/01/1990',1);
INSERT INTO ESTUDIANTE (NOMBRES, APELLIDOS, FECHANACIMIENTO, HABILITADO) VALUES ('JORGE', 'GIRALGO', '01/02/1991',1);
INSERT INTO ESTUDIANTE (NOMBRES, APELLIDOS, FECHANACIMIENTO, HABILITADO) VALUES ('SANDRA PATRICIA', 'ORTIZ PEDROZA', '01/10/1994',1);
INSERT INTO ESTUDIANTE (NOMBRES, APELLIDOS, FECHANACIMIENTO, HABILITADO) VALUES ('PEDRO ANTONIO', 'PEREA RODRIGUEZ', '01/02/1995',1);
INSERT INTO ESTUDIANTE (NOMBRES, APELLIDOS, FECHANACIMIENTO, HABILITADO) VALUES ('LUISA MARIA', 'PEREA RODRIGUEZ', '01/03/1992',1);
INSERT INTO ESTUDIANTE (NOMBRES, APELLIDOS, FECHANACIMIENTO, HABILITADO) VALUES ('MARIA HELENA', 'PEREA RODRIGUEZ', '01/04/1994',1);
INSERT INTO ESTUDIANTE (NOMBRES, APELLIDOS, FECHANACIMIENTO, HABILITADO) VALUES ('ROBINSON', 'PEREA RODRIGUEZ', '01/01/1992',1);
INSERT INTO ESTUDIANTE (NOMBRES, APELLIDOS, FECHANACIMIENTO, HABILITADO) VALUES ('IVAN CAMILO', 'MENDOZA GONZALEZ', '01/01/1993',1);
COMMIT TRAN;

SELECT * FROM ESTUDIANTE;

--INSERT TABLA PROFESOR
BEGIN TRAN
INSERT INTO PROFESOR (NOMBRES, APELLIDOS, FECHANACIMIENTO, HABILITADO) VALUES ('HERNAN', 'RODRIGUEZ', '01/01/1960',1);
INSERT INTO PROFESOR (NOMBRES, APELLIDOS, FECHANACIMIENTO, HABILITADO) VALUES ('JUAN CARLOS', 'RODRIGUEZ', '01/01/1958',1);
INSERT INTO PROFESOR (NOMBRES, APELLIDOS, FECHANACIMIENTO, HABILITADO) VALUES ('RODRIGO', 'RODRIGUEZ', '01/01/1940',1);
INSERT INTO PROFESOR (NOMBRES, APELLIDOS, FECHANACIMIENTO, HABILITADO) VALUES ('CARLOS', 'BALLESTEROS', '01/01/1956',1);
INSERT INTO PROFESOR (NOMBRES, APELLIDOS, FECHANACIMIENTO, HABILITADO) VALUES ('JHON ALEXANDER', 'RODRIGUEZ', '01/01/1960',1);
INSERT INTO PROFESOR (NOMBRES, APELLIDOS, FECHANACIMIENTO, HABILITADO) VALUES ('DIEGO ANDRES', 'RODRIGUEZ', '01/01/1960',1);
INSERT INTO PROFESOR (NOMBRES, APELLIDOS, FECHANACIMIENTO, HABILITADO) VALUES ('JAIME', 'CASTIBLANCO', '01/01/1960',1);
COMMIT TRAN;

SELECT * FROM PROFESOR;

--INSERT TABLA ASIGNATURA
BEGIN TRAN
INSERT INTO ASIGNATURA (DESCRIPCION, ACTIVA) VALUES ('ALGEBRA LINEAL',1);
INSERT INTO ASIGNATURA (DESCRIPCION, ACTIVA) VALUES ('ESTADISTICA',1);
INSERT INTO ASIGNATURA (DESCRIPCION, ACTIVA) VALUES ('INGLES',1);
INSERT INTO ASIGNATURA (DESCRIPCION, ACTIVA) VALUES ('FISICA I',1);
INSERT INTO ASIGNATURA (DESCRIPCION, ACTIVA) VALUES ('PRACTICAS',1);
INSERT INTO ASIGNATURA (DESCRIPCION, ACTIVA) VALUES ('ECONOMIA',1);
INSERT INTO ASIGNATURA (DESCRIPCION, ACTIVA) VALUES ('ETICA',1);
COMMIT TRAN;

SELECT * FROM ASIGNATURA;

--INSERT TABLA EST_PROF

BEGIN TRAN
INSERT INTO EST_PROF (IDPROFESOR, IDCLASE, IDESTUDIANTE) VALUES (1,1,2);
INSERT INTO EST_PROF (IDPROFESOR, IDCLASE, IDESTUDIANTE) VALUES (2,2,1);
INSERT INTO EST_PROF (IDPROFESOR, IDCLASE, IDESTUDIANTE) VALUES (2,2,2);
INSERT INTO EST_PROF (IDPROFESOR, IDCLASE, IDESTUDIANTE) VALUES (1,1,5);
INSERT INTO EST_PROF (IDPROFESOR, IDCLASE, IDESTUDIANTE) VALUES (2,2,7);
COMMIT TRAN;

SELECT * FROM EST_PROF;

/*       _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
		|																		|
		| CONSULTAR LOS ALUMNOS QUE TIENE ASIGNADO CADA PROFESOR POR ASIGNATURA |
		|_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _|
*/

SELECT PF.NOMBRES,
	   PF.APELLIDOS,
	   A.DESCRIPCION,
	   ES.NOMBRES,
	   ES.APELLIDOS
FROM EST_PROF EP
JOIN ESTUDIANTE ES ON EP.IDESTUDIANTE = ES.IDESTUDIANTE
JOIN PROFESOR PF ON EP.IDPROFESOR = PF.IDPROFESOR
JOIN ASIGNATURA A ON EP.IDCLASE = A.IDCLASE

/*       _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
		|																		|
		| CONSULTAR ALUMNOS POR NOMBRE UTILIZANDO UN SP  					    |
		|_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _|
*/

CREATE PROCEDURE CONSULTAR_ALUMNOS

  @Nombre varchar(30)

 as

 Begin

  SELECT NOMBRES, APELLIDOS
   FROM ALUMNOS
   WHERE NOMBRES LIKE @Nombre;
   END

 GO


 EXEC CONSULTAR_ALUMNOS 'JORGE'


 /*       _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
		|																		|
		| VISTA PARA CONSULTAR LAS ASIGNATURAS DE CADA PROFESOR				    |
		|_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _|
*/


 CREATE VIEW VW_PROF_ASIGNATURA AS 
	SELECT PF.NOMBRES,
	       PF.APELLIDOS,
		   A.DESCRIPCION AS CLASE
 FROM PROFESOR PF
 JOIN EST_PROF EP ON PF.IDPROFESOR = EP.IDPROFESOR
 JOIN ASIGNATURA A ON A.IDCLASE = EP.IDCLASE;

 SELECT * FROM VW_PROF_ASIGNATURA;